### ISSUE TITLE
url 

### ISSUE THREAD

**Issue by isaiahsip** [NovaAppsInc/fracital-static#6]
![Screenshot 2022-04-13 1 01 30 PM](https://user-images.githubusercontent.com/48495357/163232612-1de17b9b-e5e5-4414-9432-2a028496ae00.png)

says that valid urls are not urls

followed directions exactly as it said

**Comment by isaiahsip** [comment]
did not make any edits after cloning to the replit

**Comment by NovaAppsInc** [comment]
we know about this
